# Create a AWS SAM file to deploy a Lambda for a todo application.
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html
Transform: AWS::Serverless-2016-10-31

Resources:
  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: todo_app.get_root
      Runtime: python3.10
      CodeUri: .
      Events:
        TodoApi:
          Type: Api
          Properties:
            Path: /todos
            Method: get
